<!DOCTYPE html>
<?php
require_once "{$_SERVER['DOCUMENT_ROOT']}/HelpRpg/class/view/tags.class.php";
require_once "{$_SERVER['DOCUMENT_ROOT']}/HelpRpg/rotas/rotas-url.php";
$tag = new Tags();

$tag->html();
    $tag->head();
        $tag->link(['href'=>ROOTPATHURL.CSSPATH.'bootstrap.min.css', 'rel'=>'stylesheet']);
        $tag->link(['href'=>'../css/fonts.css', 'rel'=>'stylesheet']);
        $tag->link(['href'=>'css/index.css', 'rel'=>'stylesheet']);
        $tag->link(['rel'=>'stylesheet', 'href'=>ROOTPATHURL.CSSPATH.'bootstrap-select.css', ]);
    $tag->head;

    $tag->div(['class'=>'container']);
        $tag->div(['class'=>'row']);
            $tag->div(['class'=>'col-md-12']);
                $tag->h2();
                    $tag->printer('Gerador de nomes - Help RPG');
                $tag->h2;
                $tag->printer('|');
                $tag->a(['href'=>'../index.php']);
                    $tag->printer('Home');
                $tag->a;
                $tag->printer('|');
                 $tag->a(['href'=>'lugares.php']);
                    $tag->printer('Lugares');
                $tag->a;
                $tag->printer('|');
                 $tag->a(['href'=>'classes.php']);
                    $tag->printer('Classes');
                $tag->a;
                $tag->printer('|');
                 $tag->a(['href'=>'../nomes/']);
                    $tag->printer('Raças');
                $tag->a;
                $tag->printer('|');
                 $tag->a(['href'=>'culturais.php']);
                    $tag->printer('Culturais');
                $tag->a;
                $tag->printer('|');
                 $tag->a(['href'=>'outros.php']);
                    $tag->printer('Outros');
                $tag->a;
                $tag->printer('|');
                $tag->printer('Criado por Maickon Rangel - ');
                 $tag->a(['href'=>ROOTPATHURL]);
                    $tag->printer('helprpg.com.br');
                $tag->a;
            $tag->div;
            $tag->hr();
        $tag->div;