<?php
define("CON_DAEMON","CON");
define("FOR_DAEMON","FOR");
define("DEX_DAEMON","DEX");
define("AGI_DAEMON","AGI");
define("INT_DAEMON","INT");
define("PER_DAEMON","PER");
define("CAR_DAEMON","CAR");
define("WILL_DAEMON","WILL");
define("IP_DAEMON","Índice de Proteção");
define("PV_DAEMON","Pontos de Vida");
define("PH_DAEMON","Pontos Heróicos");
define("PM_DAEMON","Pontos de Magia");
define("PF_DAEMON","Pontos de Fé");
define("PERICIAS_COM_ARMAS_DAEMON","Perícias com Armas");
define("APRIMORAMENTOS_DAEMON","Aprimoramentos");
define("NASCIDO_NO_DIA","Nascido no Dia");
define("LOCAL_DE_NASCIMENTO","Local de Nascimento");
define("PROFISSAO","Classe/Profissão");
define("IDADE_APARENTE","Idade Aparente");
define("IDADE_REAL","Idade Real");
define("RELIGIAO","Religião");