<?php
define("FORCA","Força");
define("AGILIDADE","Agilidade");
define("ASTUCIA","Astúcia");
define("PERICIAS","Perícias");
define("ESPIRITO","Espírito");
define("VIGOR","Vigor");
define("COMPLICACOES","Complicações");
define("ATAQUES","Ataques");
define("DANO","Dano");
define("VANTAGENS","Vantagens");
define("AVANCOS","Avanços");
define("EQUIPAMENTOS","Equipamentos");
