<?php
define("CON_DAEMON","CON");
define("FOR_DAEMON","STR");
define("DEX_DAEMON","DEX");
define("AGI_DAEMON","AGI");
define("INT_DAEMON","INT");
define("PER_DAEMON","PER");
define("CAR_DAEMON","CHA");
define("WILL_DAEMON","WILL");
define("IP_DAEMON","Protection Index");
define("PV_DAEMON","Health points");
define("PH_DAEMON","Heroic points");
define("PM_DAEMON","Magic Points");
define("PF_DAEMON","Faith points");
define("PERICIAS_COM_ARMAS_DAEMON","Skills Weapon");
define("APRIMORAMENTOS_DAEMON","Enhancements");
define("NASCIDO_NO_DIA","Born on the Day");
define("LOCAL_DE_NASCIMENTO","Birthplace");
define("PROFISSAO","Class/Profession");
define("IDADE_APARENTE","Apparent Age");
define("IDADE_REAL","Real age");
define("RELIGIAO","Religion");