<?php
define("FORCA","Force");
define("AGILIDADE","Agility");
define("ASTUCIA","Cunning");
define("PERICIAS","Expertise");
define("ESPIRITO","Spirit");
define("VIGOR","Vigor");
define("COMPLICACOES","omplications");
define("ATAQUES","Attacks");
define("DANO","Damage");
define("VANTAGENS","Advantages");
define("AVANCOS","Advances");
define("EQUIPAMENTOS","Equipments");
