// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// js/name_set.js
//
// Escrito por Maickon
// http://creativecommons.org/licenses/by-nc/3.0/

var nomes = [
        'Charlatão',
        'Criminoso',
        'Animador',
        'Herói do Povo',
        'Artesão de Guilda',
        'Eremita',
        'Nobre',
        'Aviadado',
        'Machista',
        'Mandão',
        'Viciado',
        'Chorão',
        'Infantil',
        'Cuzão',
        'Oportunista',
        'Ganancioso',
        'Apaixonado',
        'Pintor',
        'Desenhista',
        'Fanático',
        'Forasteiro',
        'Sábio',
        'Orfão',
		'Chato', 
		'Humorado (Bom humor)', 
		'Invejoso', 
		'Maldoso)', 
		'Gentil', 
		'Safado (Golpista)', 
		'Safado (Mulheres)', 
		'Mulherengo', 
		'Assassino',
		'Pegador',
		'Mentiroso', 
		'Bondoso', 
		'Idiota', 
		'Imbecil', 
		'Bobo (Ser Babaca)',
		'Bobo (Ser passado pra trás)',
		'Metido a Espertalhão', 
		'Andrógeno', 
		'Metido a Machão',
		'Gay', 
		'Homofóbico',
		'Medroso',
		'Racista',
		'Corajoso', 
		'Medo de Insetos', 
		'Medo de Mulher', 
		'Medo de Escuro', 
		'Tímido', 
		'Vigarista', 
		'Vacilão',
		'Sapatão', 
		'Homofóbico',
		'Esconde Segredos', 
		'Arrogante', 
		'Despresível', 
		'Estuprador', 
		'Falador', 
		'Desafiador', 
		'Estudioso',
	 	'Justo', 
	 	'Compulsivo', 
	 	'Irritante', 
	 	'Respeitado', 
	 	'Apavorado', 
	 	'Apavorador', 
	 	'Intimidador', 
	 	'Feio', 
	 	'Atraente', 
	 	'Bonito',
		'Capitalista', 
		'Calmo', 
		'Chapado', 
		'Atento', 
		'Sério',
		'Brincalhão',
		'Inparcial', 
		'Opressor', 
		'Tirano',
		'Corrupto',
		'Corruptível',
		'Intolerante',
		'Bruto',
		'Selvagem',
		'Fumante', 
		'Vício',
		'Inocente', 
		'Lider',
		'Honrado',
		'Sem emoção',
		'Coração frio',
		'Soberbo',
		'Agressivo',
		'Alegre',
		'Autruista',
		'Ambicioso',
		'Amoroso',
		'Ansioso',
		'Antipático',
		'simpático',
		'Atrevido',
		'Alienado',
		'Audacioso',
		'Bondoso',
		'Bisbilhoteiro',
		'birrento',
		'beijoqueiro',
		'brusco',
		'bebado',
		'crédulo',
		'comodista',
		'comunicativo',
		'cínico',
		'ciumento',
		'compreensivo',
		'caridoso',
		'criativo',
		'cómico',
		'covarde',
		'canalha',
		'calado',
		'Desiquilibrado',
		'Distraído',
		'Depressivo',
		'Dorminhoco',
		'Doentio',
		'Dócil',
		'Delicado',
		'Desconfiado',
		'Super dotado',
		'Disciplinado',
		'Egoista',
		'Educado',
		'Extravagante',
		'Extrovertido',
		'Equilibrado',
		'Envergonhado',
		'Esforçado',
		'Emotivo',
		'Exigente',
		'Excêntrico',
		'Escrupuloso',
		'Elegante',
		'Enigmatico',
		'Flexível',
		'Fútil',
		'Feliz',
		'Franco',
		'Falso',
		'Fiel',
		'Fofoqueiro',
		'Finjido',
		'Farsante',
		'Fanfarrão',
		'Generoso',
		'Guloso',
		'Hipócrita',
		'Honesto',
		'Humilde',
		'Indiferente',
		'Interesseiro',
		'Intrometido',
		'Infiel',
		'Irracional',
		'Injusto',
		'Impedioso',
		'Impuro',
		'Indelicado',
		'Incompetente',
		'Ingénuo',
		'Ignorante',
		'Imaturo',
		'Ingrato',
		'Irresponsavel'
		
];
//http://lenaeosegredo.blogspot.com.br/2009/10/qualidades-e-defeitos-de-a-z.html

var classes = [
        'Guerreiro',
        'Mago',
        'Feiticeiro',
        'Bruxo',
        'Samaritano',
        'Clérigo',
        'Samurai',
        'Monge',
        'Ranger',
        'Bardo',
        'Paladino',
        'Soldado',
        'Gladiador',
        'Bárbaro',
        'Arqueiro',
        'Alquimista',
        'Ninja',
        'Pirata'
];
//http://universo-rpg.blogspot.com.br/p/racas.html
//http://dnd5th.blogspot.com.br/2015/02/antecedente-cacador-de-monstros.html

var racas = [
        'Humano',
        'Elfo',
        'Meio-elfo',
        'Draconato',
        'Orc',
        'Meio-orc',
        'Helfling',
        'Anão',
        'Dríade',
        'Fada',
        'Meio-dragão',
        'Meio-abssal',
        'Meio-celestial',
        'Duende',
        'Eladrin',
        'Hobbit',
        'Goblin',
        'Golias',
        'wemics',
        'Furry',
        'Gabirús',
        'Sahuagin',
        'Gnoll',
        'Hadozee',
        'Automatoi',
        'Wendigo',
        'Khajiit',
        'Homem Urso',
        'Viera',
        'warforged',
        'Thri-Kreen',
        'Ganeshins',
        'Drows',
        'Kobold',
        'Faunos',
        'Sátiro',
        'Aesires',
        'Morto-vivo',
        'Troll',
        'Vanires',
        'Troglodita',
        'Hobgoblin',
        'Doppelganger',
        'Yuan-ti',
        'Illumians',
        'Turto',
        'Centauro',
        'Dragotauro',
        'Revants',
        'Bullywung',
        'Tiefling',
        'Lissit',
        'Gorka',
        'Sereia',
        'Tritão',
        'Paskkin',
        'Nagahs',
        'Bugbear',
        'Dohtrohs',
        'Youkai',
        'Vampiro',
        'Gárgula'
];

function load_caracteristica(){    
    var classe_name  = document.getElementById("classes");
    var raca_name    = document.getElementById("racas");
    
	var classe_selecionada  = classe_name.options[classe_name.selectedIndex].text;
	var raca_selecionada    = raca_name.options[raca_name.selectedIndex].text;

    if(classe_selecionada == ''){
        sorteio_palavras(classes, "campo_classe");
    }else{
        document.getElementById("campo_classe").value = classe_selecionada;
    }
    
    if(raca_selecionada == ''){
        sorteio_palavras(racas, "campo_raca");
    }else{
        document.getElementById("campo_raca").value = raca_selecionada;
    }
     
	var campos = ['campo1','campo2','campo3','campo4'];
	var id_hab = ['hab1','hab2','hab3','hab4','hab5','hab6'];
	
	for(var i=0; i<=8; i++){
		sorteio_palavras(nomes, campos[i]);
	}
	
	for(var i=0; i<=8; i++){
		sorteio_numeros(id_hab[i]);
	}
}
