<?php 
function helper_show_personagens_ded4_0($personagem){
	global $tag, $form;
	$unserialize_params = unserialize($personagem['dados']);
	
	$tag->div('class="col-md-12 header_ded_4-0"');
		$form->_row();
			$form->_col(6);
				$tag->imprime($form->bold($personagem['nome']));
			$form->col_();
			$form->_col(6);
				$tag->imprime($form->bold(CODIGO).$personagem['id']);
			$form->col_();
			$form->_col(6);
				$tag->imprime($form->bold($personagem['sistema']));
			$form->col_();
			$form->_col(6);
				$tag->imprime($form->bold(CRIADOR.' ('.$personagem['dono'].')'));				
			$form->col_();
			$form->_col(6);
				$tag->imprime($form->bold($personagem['raca'].' '.$personagem['classe']));	
				$tag->br();
				$tag->imprime('Humanóide('.$unserialize_params['tamanho'].')');
			$form->col_();
			$form->_col(6);
				$tag->imprime($form->bold('Personagem de Nível '.$personagem['lv']));
				$tag->br();
				$tag->imprime(XP.' '.$unserialize_params['xp']);
			$form->col_();
		$form->row_();
	$tag->div;	
	$tag->div('class="col-md-12 body1_ded_4-0"');
		$form->_row();
			$form->_col(6);
				$tag->imprime($form->bold(INICIATIVA).$unserialize_params['iniciativa']);
			$form->col_();
			
			$form->_col(6);
				$tag->imprime($form->bold(SENTIDOS).' '.PERCEPCAO.' +'.$unserialize_params['percepcao_passiva']);	
			$form->col_();
		$form->row_();
	$tag->div;	
	$tag->div('class="col-md-12 body1_ded_4-0"');
		$form->_row();
			$form->_col(12);
				$tag->imprime($form->bold(PONTOS_VODA).' '.$unserialize_params['pv']);
			$form->col_();
		$form->row_();
	$tag->div;	
	
	$tag->div('class="col-md-12 body1_ded_4-0"');
		$form->_row();
			$form->_col(12);
				$tag->imprime($form->bold(CA).' '.$unserialize_params['ca'].';');
				$tag->imprime($form->bold(FORTITUDE).' '.$unserialize_params['fort'].';');
				$tag->imprime($form->bold(VONTADE).' '.$unserialize_params['vont'].';');
				$tag->imprime($form->bold(REFLEXO).' '.$unserialize_params['refl'].';');
			$form->col_();
		$form->row_();
	$tag->div;	
	
	$tag->div('class="col-md-12 body1_ded_4-0"');
		$form->_row();
			$form->_col(12);
				$tag->imprime($form->bold(DESL).' '.$unserialize_params['deslocamento'].';');
			$form->col_();
		$form->row_();
	$tag->div;	
	
	$tag->div('class="col-md-12 body2_ded_4-0"');
		$form->_row();
			$form->_col(6);
				$tag->imprime($form->bold(CAMINHO_EXEMPLAR).' '.$unserialize_params['caminho_exemplar'].';');
			$form->col_();
			$form->_col(6);
				$tag->imprime($form->bold(DESTINO_EPICO).' '.$unserialize_params['destino_epico'].';');
			$form->col_();
			$form->_col(6);
				$tag->imprime($form->bold(TENDENCIA).' '.$unserialize_params['tendencia'].';');
			$form->col_();
		$form->row_();
	$tag->div;	
	
	$tag->div('class="col-md-12 body2_ded_4-0"');
		$form->_row();
			$form->_col(6);
				$tag->imprime($form->bold(IDADE).' '.$unserialize_params['idade'].';');
			$form->col_();
			$form->_col(6);
				$tag->imprime($form->bold(ALTURA).' '.$unserialize_params['altura'].';');
			$form->col_();
			$form->_col(6);
				$tag->imprime($form->bold(PESO).' '.$unserialize_params['peso'].';');
			$form->col_();
			$form->_col(6);
				$tag->imprime($form->bold(SEXO).' '.$unserialize_params['sexo'].';');
			$form->col_();
			$form->_col(6);
				$tag->imprime($form->bold(IDIOMAS).' '.$unserialize_params['idiomas'].';');
			$form->col_();
			$form->_col(6);
				$tag->imprime($form->bold(DIVINDADE).' '.$unserialize_params['divindade'].';');
			$form->col_();
			$form->_col(6);
				$tag->imprime($form->bold(ORIGEM_LOCAL).' '.$unserialize_params['regiao_origem'].';');
			$form->col_();
		$form->row_();
	$tag->div;	
	
	$tag->div('class="col-md-12 body1_ded_4-0"');
		$form->_row();
			$form->_col(6);
				$tag->imprime($form->bold(INTUICAO_PASSIVA).' '.$unserialize_params['intuicao_passiva'].';');
			$form->col_();
			$form->_col(6);
				$tag->imprime($form->bold(PERCEPCAO_PASSIVA).' '.$unserialize_params['percepcao_passiva'].';');
			$form->col_();
			$form->_col(6);
				$tag->imprime($form->bold(SANGRANDO).' '.$unserialize_params['sangrando'].';');
			$form->col_();
			$form->_col(6);
				$tag->imprime($form->bold(PULSO_DE_CURA).' '.$unserialize_params['pulso_cura'].';');
			$form->col_();
			$form->_col(6);
				$tag->imprime($form->bold(PULSOS).' '.$unserialize_params['pulsos'].';');
			$form->col_();
			$form->_col(6);
				$tag->imprime($form->bold(PONTO_DE_ACAO).' '.$unserialize_params['pts_acao'].';');
			$form->col_();
		$form->row_();
	$tag->div;	
	
	$tag->div('class="col-md-12 body2_ded_4-0"');
		$form->_row();
			$form->_col(4);
				$tag->imprime($form->bold(FORCA)."{$unserialize_params['forca']}".' ('.mod($unserialize_params['forca']).')');
			$form->col_();
			$form->_col(4);
				$tag->imprime($form->bold(CON)."{$unserialize_params['constituicao']}".' ('.mod($unserialize_params['constituicao']).')');
			$form->col_();
			$form->_col(4);
				$tag->imprime($form->bold(DES)."{$unserialize_params['destreza']}".' ('.mod($unserialize_params['destreza']).')');
			$form->col_();
			$form->_col(4);
				$tag->imprime($form->bold(INTELIGENCIA)."{$unserialize_params['inteligencia']}".' ('.mod($unserialize_params['inteligencia']).')');
			$form->col_();
			$form->_col(4);
				$tag->imprime($form->bold(SAB)."{$unserialize_params['sabedoria']}".' ('.mod($unserialize_params['sabedoria']).')');
			$form->col_();
			$form->_col(4);
				$tag->imprime($form->bold(CAR)."{$unserialize_params['carisma']}".' ('.mod($unserialize_params['carisma']).')');
			$form->col_();
		$form->row_();
	$tag->div;
	
	$tag->div('class="col-md-12 body1_ded_4-0"');
		$form->_row();
			$form->_col(6);
				$tag->imprime($form->bold(BONUS_DE_ATAQUE).' '.$unserialize_params['ataque'].';');
			$form->col_();
			$form->_col(6);
				$tag->imprime($form->bold(BONUS_DE_DANO).' '.$unserialize_params['dano'].';');
			$form->col_();
			$form->_col(12);
				$tag->imprime($form->bold(ATAQUE_BASICO).'<br>'.$unserialize_params['ataque_basico']);
			$form->col_();
		$form->row_();
	$tag->div;
	
	$tag->div('class="col-md-12 body1_ded_4-0"');
		$form->_row();
			$form->_col(12);
				$tag->imprime($form->bold(PERICIAS).' '.$unserialize_params['pericias'].';');
			$form->col_();
			$form->_col(6);
				$tag->imprime($form->bold(PULSO_DE_CURA).' '.$unserialize_params['pulso_cura'].';');
			$form->col_();
			$form->_col(6);
				$tag->imprime($form->bold(PULSOS).' '.$unserialize_params['pulsos'].';');
			$form->col_();
			$form->_col(6);
				$tag->imprime($form->bold(PONTO_DE_ACAO).' '.$unserialize_params['pts_acao'].';');
			$form->col_();
		$form->row_();
	$tag->div;	
	
	$tag->div('class="col-md-12 body2_ded_4-0"');
		$form->_row();
			$form->_col(12);
				$tag->imprime($form->bold(TALENTOS).'<br>'.$unserialize_params['talentos']);
			$form->col_();
			$form->_col(12);
				$tag->imprime($form->bold(ASPECTOS_RACIAIS).'<br>'.$unserialize_params['aspectos_raciais']);
			$form->col_();
			$form->_col(12);
				$tag->imprime($form->bold(CARACTERISTICAS_CLASSE_TRILHA_DESTINO).'<br>'.$unserialize_params['caracteristicas']);
			$form->col_();
			$form->_col(12);
				$tag->imprime($form->bold(PODERES).'<br>'.$unserialize_params['poderes']);
			$form->col_();
		$form->row_();
	$tag->div;	
	
	$tag->div('class="col-md-12 body1_ded_4-0 border-button"');
		$form->_row();
			$form->_col(12);
				$tag->imprime($form->bold(ITENS_ESQUIPAMENTOS).'<br>'.$unserialize_params['equipamentos']);
			$form->col_();
			$form->_col(12);
				$tag->imprime($form->bold(HABILIDADES_ESPECIAIS).'<br>'.$unserialize_params['habilidades_especiais']);
			$form->col_();
			$form->_col(12);
				$tag->imprime($form->bold(COSTUMES_APARENCIA).'<br>'.$unserialize_params['costumes']);
			$form->col_();
			$form->_col(12);
				$tag->imprime($form->bold(TRACOS_PERSONALIDADE).'<br> '.$unserialize_params['tracos']);
			$form->col_();
		$form->row_();
	$tag->div;		
	
}