// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// js/name_set.js
//
// Escrito por Maickon
// http://creativecommons.org/licenses/by-nc/3.0/

var nomes = [
             'Charlatão',
             'Criminoso',
             'Animador',
             'Herói do Povo',
             'Artesão de Guilda',
             'Eremita',
             'Nobre',
             'Aviadado',
             'Machista',
             'Mandão',
             'Viciado',
             'Chorão',
             'Infantil',
             'Cuzão',
             'Oportunista',
             'Ganancioso',
             'Apaixonado',
             'Pintor',
             'Desenhista',
             'Fanático',
             'Forasteiro',
             'Sábio',
             'Orfão',
     		'Chato', 
     		'Humorado (Bom humor)', 
     		'Invejoso', 
     		'Maldoso)', 
     		'Gentil', 
     		'Safado (Golpista)', 
     		'Safado (Mulheres)', 
     		'Mulherengo', 
     		'Assassino',
     		'Pegador',
     		'Mentiroso', 
     		'Bondoso', 
     		'Idiota', 
     		'Imbecil', 
     		'Bobo (Ser Babaca)',
     		'Bobo (Ser passado pra trás)',
     		'Metido a Espertalhão', 
     		'Andrógeno', 
     		'Metido a Machão',
     		'Gay', 
     		'Homofóbico',
     		'Medroso',
     		'Racista',
     		'Corajoso', 
     		'Medo de Insetos', 
     		'Medo de Mulher', 
     		'Medo de Escuro', 
     		'Tímido', 
     		'Vigarista', 
     		'Vacilão',
     		'Sapatão', 
     		'Homofóbico',
     		'Esconde Segredos', 
     		'Arrogante', 
     		'Despresível', 
     		'Estuprador', 
     		'Falador', 
     		'Desafiador', 
     		'Estudioso',
     	 	'Justo', 
     	 	'Compulsivo', 
     	 	'Irritante', 
     	 	'Respeitado', 
     	 	'Apavorado', 
     	 	'Apavorador', 
     	 	'Intimidador', 
     	 	'Feio', 
     	 	'Atraente', 
     	 	'Bonito',
     		'Capitalista', 
     		'Calmo', 
     		'Chapado', 
     		'Atento', 
     		'Sério',
     		'Brincalhão',
     		'Inparcial', 
     		'Opressor', 
     		'Tirano',
     		'Corrupto',
     		'Corruptível',
     		'Intolerante',
     		'Bruto',
     		'Selvagem',
     		'Fumante', 
     		'Vício',
     		'Inocente', 
     		'Lider',
     		'Honrado',
     		'Sem emoção',
     		'Coração frio',
     		'Soberbo',
     		'Agressivo',
     		'Alegre',
     		'Autruista',
     		'Ambicioso',
     		'Amoroso',
     		'Ansioso',
     		'Antipático',
     		'simpático',
     		'Atrevido',
     		'Alienado',
     		'Audacioso',
     		'Bondoso',
     		'Bisbilhoteiro',
     		'birrento',
     		'beijoqueiro',
     		'brusco',
     		'bebado',
     		'crédulo',
     		'comodista',
     		'comunicativo',
     		'cínico',
     		'ciumento',
     		'compreensivo',
     		'caridoso',
     		'criativo',
     		'cómico',
     		'covarde',
     		'canalha',
     		'calado',
     		'Desiquilibrado',
     		'Distraído',
     		'Depressivo',
     		'Dorminhoco',
     		'Doentio',
     		'Dócil',
     		'Delicado',
     		'Desconfiado',
     		'Super dotado',
     		'Disciplinado',
     		'Egoista',
     		'Educado',
     		'Extravagante',
     		'Extrovertido',
     		'Equilibrado',
     		'Envergonhado',
     		'Esforçado',
     		'Emotivo',
     		'Exigente',
     		'Excêntrico',
     		'Escrupuloso',
     		'Elegante',
     		'Enigmatico',
     		'Flexível',
     		'Fútil',
     		'Feliz',
     		'Franco',
     		'Falso',
     		'Fiel',
     		'Fofoqueiro',
     		'Finjido',
     		'Farsante',
     		'Fanfarrão',
     		'Generoso',
     		'Guloso',
     		'Hipócrita',
     		'Honesto',
     		'Humilde',
     		'Indiferente',
     		'Interesseiro',
     		'Intrometido',
     		'Infiel',
     		'Irracional',
     		'Injusto',
     		'Impedioso',
     		'Impuro',
     		'Indelicado',
     		'Incompetente',
     		'Ingénuo',
     		'Ignorante',
     		'Imaturo',
     		'Ingrato',
     		'Irresponsavel'
];
console.log(nomes.length);
function load_caracteristica(){
	var campos = ['campo1','campo2','campo3','campo4'];
	for(var i=0; i<=8; i++){
		sorteio_palavras(nomes, campos[i]);
	}
}
